### ISSUE TITLE
Issue in the way OkHttpClient is used in the Minio Java Client

### ISSUE THREAD

**Issue by someshrathi02** [minio/minio-java#628]
These seems to be an issue in the way OkHttpClient is used in the Minio Java Client

*Context:*
We are trying to connect to Minio using the Mimio-java client from a SpringBoot application.
+ JDK 1.8.0_112
+ Minio Client - 3.0.7

The SpringBoot application is using a custom PKI provider.

Issue faced:
It looks like Minio Java client is using the OKHTTPClient. And the problem appears to be how Minio Java client is using the OkHttPClient.

https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/MinioClient.java  

So even though Minio Java Client provides a constructor to pass the OkHttpClient (see below), it is already initializing the OkHttpClient at the Class level in line 202:

This is the constructor that we want to use
`MinioClient(String endpoint, int port, String accessKey, String secretKey, String region, boolean secure, OkHttpClient httpClient)`

line 202
`private OkHttpClient httpClient = new OkHttpClient();`

So if this httpClient initialization is moved to the relevant Constructors (& not at the class level), we think that the issue can be resolved.

The problem happens when the default OkHttpClient tries to set the default TrustManager:

Within the OkHttpClient
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.java 
Line 284
`trustManagerFactory.init((KeyStore) null);`
Not all the custom PKI providers handle this null gracefully.

*Work around (used for now):*
We switched from using the Minio Java Client to AmazonS3 Java client and everything works as expected.

**Comment by balamurugana** [comment]
@someshrathi02 The issue is already fixed in the master by https://github.com/minio/minio-java/pull/621.  Could you check that?

**Comment by balamurugana** [comment]
@someshrathi02 There is new release available http://central.maven.org/maven2/io/minio/minio/3.0.8/

**Comment by someshrathi02** [comment]
Hi Balamurugana ,
 Thanks for your reply. #621 is related to increasing default timeout. 

However this one is related to line 202 where httpClient is intialized using new operator.




line 202
private OkHttpClient httpClient = new OkHttpClient();

So if this httpClient initialization is moved to the relevant Constructors (& not at the class level), we think that the issue can be resolved.

**Comment by balamurugana** [comment]
@someshrathi02 I am unable to understand why ` private OkHttpClient httpClient = new OkHttpClient();` is problem in the constructor accepting custom OkHttpClient.

Could you try latest minio-java?

**Comment by ramkumarkb** [comment]
@balamurugana We have tested the latest version and the issue persists (and therefore we have to continue to use the Amazon Java Client).

We think the real cause is the line (line 202):

`private OkHttpClient httpClient = new OkHttpClient();`

From our analysis, even before the constructor initializes the httpClient with the passed in Object, the Class level initialization takes place (as per the Java initialization process of new Objects). That is line 202 gets executed before the Constructor's httpClient is passed.

And this causes the issue as the custom PKI Provider is unable to handle null. If this initialization of httpClient is moved to each of the constructors, then we should be good.

https://stackoverflow.com/questions/23093470/java-order-of-initialization-and-instantiation

**Comment by balamurugana** [comment]
@ramkumarkb 
I am aware of class level initialization by `private OkHttpClient httpClient = new OkHttpClient();`.  That why we have provided custom HTTP client way to override it.  Refer http://minio.github.io/minio-java/io/minio/MinioClient.html#MinioClient-java.lang.String-int-java.lang.String-java.lang.String-java.lang.String-boolean-okhttp3.OkHttpClient-

Isn't this solution fixing your problem?

**Comment by someshrathi02** [comment]
@balamurugana 
   we agree that we have an option to pass in the custom OkHTTPClient, but we are not able to avoid the default initialisation of the OKHTTPClient as its in the class level which is causing issue for us. Even though we pass the custom OkHTTPClient, MinioClient tries to first initialise the default OkHTTPClient and throws error in our case before it assigns the custom one.

**Comment by balamurugana** [comment]
@someshrathi02 
Could you share exact error message you are getting?  If possible you can share a sample code which causes the problem

**Comment by someshrathi02** [comment]
@balamurugana 
   Unfortunately we will not be able to share a sample code which causes the problem as it has our custom PKI implementation dependency. 

The OKHttpClient is trying to setup the systemDefaultTrustManager, see below code.

From https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.java (Line 280)

      TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(
          TrustManagerFactory.getDefaultAlgorithm());
      trustManagerFactory.init((KeyStore) null);

In case of JDK implementation of TrustManagerFactoryImpl, the init with null keystore is handled. So when we use the default implementation, there will not be any issues. 
As we are using our custom PKI implementation which doesn't setup the TrustManager when the init is called with null keystore. 
When the next line in OKHttpClient is called 
[ TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();]
It throws an error.
So even though there is an option to pass our custom OKHTTPClient, due to the class level initialisation of the OKHTTPClient is restricting us.

**Comment by ramkumarkb** [comment]
@balamurugana
We noticed that you marked the issue as low and moved it out of the current milestone. Request you to reconsider your decision.

Since one can not control the behavior of a custom PKI provider, removing the default initialization would be favorable approach.

Thank you,

**Comment by balamurugana** [comment]
@someshrathi02 @ramkumarkb I sent a PR fixing this issue.  Please check whether it works for you.

**Comment by ramkumarkb** [comment]
@balamurugana
Thank you for the PR. We have verified this fix offline and this indeed resolves the issue!

We are now able to go back to using Minio java client instead of S3 java client.

Thank you very much for the quick turnaround. We will await the merge of this PR.

Best,
